const express=require('express'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const app=express(),SITE=(process.env.SITE_URL||'https://www.greenwayafs.com').replace(/\/$/,'');
const DIR=process.env.DATA_DIR||path.join(__dirname,'data'),FILE=path.join(DIR,'content.json');
const PASS=process.env.ADMIN_PASSWORD,SECRET=process.env.SESSION_SECRET||crypto.randomBytes(32).toString('hex');
fs.mkdirSync(DIR,{recursive:true});
if(!fs.existsSync(FILE))fs.copyFileSync(path.join(__dirname,'seed.json'),FILE);
const load=()=>JSON.parse(fs.readFileSync(FILE,'utf8')),save=d=>fs.writeFileSync(FILE,JSON.stringify(d,null,2));
const e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paras=s=>String(s||'').split(/\n\s*\n/).filter(Boolean).map(p=>`<p>${e(p)}</p>`).join('');
const lines=s=>String(s||'').split('\n').map(x=>x.trim()).filter(Boolean);
const slug=s=>String(s).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const eq=(a,b)=>{const A=Buffer.from(a),B=Buffer.from(b);return A.length===B.length&&crypto.timingSafeEqual(A,B)};
const sign=v=>crypto.createHmac('sha256',SECRET).update(v).digest('hex');
const authed=r=>{const m=/(?:^|; )s=(\d+)\.([a-f0-9]+)/.exec(r.headers.cookie||'');return !!m&&+m[1]>Date.now()&&eq(sign(m[1]),m[2])};
app.disable('x-powered-by');app.set('trust proxy',1);
app.use(express.urlencoded({extended:false,limit:'200kb'}));
app.use(express.static(path.join(__dirname,'public'),{maxAge:'1h'}));

/* ---------- public layout ---------- */
const imgOr=(src,alt,cls)=>src?`<img class="${cls}" src="${e(src)}" alt="${e(alt)}" loading="lazy">`:`<div class="${cls} ph" role="img" aria-label="${e(alt)}"></div>`;
const layout=(d,{title,desc,p='/',ld,body})=>{const s=d.site;return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(title)}</title><meta name="description" content="${e(desc)}"><link rel="canonical" href="${SITE}${p}"><meta property="og:site_name" content="${e(s.name)}"><meta property="og:title" content="${e(title)}"><meta property="og:description" content="${e(desc)}"><meta property="og:type" content="website"><meta property="og:url" content="${SITE}${p}"><meta name="twitter:card" content="summary_large_image"><link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@600;700&family=Inter:wght@400;500;600&display=swap" rel="stylesheet"><link rel="stylesheet" href="/style.css">${ld?`<script type="application/ld+json">${JSON.stringify(ld).replace(/</g,'\\u003c')}</script>`:''}</head><body>
<header class="top"><a class="brand" href="/">${e(s.name)}</a><nav><a href="/services">Services</a><a href="/projects">Projects</a><a href="/about">About</a><a href="/contact">Contact</a></nav><a class="btn sm" href="tel:${e(s.tel)}">Call ${e(s.phone)}</a></header>
<main>${body}</main>
<footer><div class="wrap cols"><div><strong>${e(s.name)}</strong><p>Athletic field construction &amp; maintenance serving ${e(s.areas)}.</p></div><div><a href="tel:${e(s.tel)}">${e(s.phone)}</a><br><a href="mailto:${e(s.email)}">${e(s.email)}</a></div><div>${s.social.map(u=>`<a href="${e(u)}" rel="noopener">${e(new URL(u).hostname.replace('www.','').split('.')[0])}</a>`).join('<br>')}</div></div><p class="copy">© ${new Date().getFullYear()} ${e(s.legalName)}</p></footer></body></html>`};
const bizLD=d=>({'@context':'https://schema.org','@type':'LocalBusiness','@id':SITE+'/#org',name:d.site.name,legalName:d.site.legalName,alternateName:d.site.formerName,url:SITE,telephone:d.site.tel,email:d.site.email,areaServed:d.site.areas.split(',').map(x=>({'@type':'State',name:x.trim()})),sameAs:d.site.social,description:'Athletic field construction, renovation and turf maintenance.'});
const projCard=p=>`<article class="card">${imgOr(p.image,p.title,'thumb')}<div class="pad"><h3>${e(p.title)}</h3><p class="meta">${e(p.location)} · ${e(p.year)}</p><ul>${lines(p.scope).slice(0,4).map(x=>`<li>${e(x)}</li>`).join('')}</ul></div></article>`;
const cta=d=>`<section class="band"><div class="wrap"><h2>Planning a field project?</h2><p>Tell us about your fields and we'll follow up with next steps.</p><a class="btn" href="/contact">Request a quote</a> <a class="btn ghost" href="tel:${e(d.site.tel)}">Call ${e(d.site.phone)}</a></div></section>`;

/* ---------- public pages ---------- */
app.get('/',(q,r)=>{const d=load(),s=d.site,feat=d.projects.filter(p=>p.featured==='yes').slice(0,6);
r.send(layout(d,{title:`${s.name} | Athletic Field Construction & Maintenance in CT & NY`,desc:`${s.name} builds, renovates and maintains athletic fields for schools, towns and leagues across ${s.areas}. 135+ years of combined experience.`,ld:bizLD(d),body:`
<section class="hero"><div class="wrap"><h1>${e(s.heroTitle)}</h1><p>${e(s.heroSub)}</p><a class="btn" href="/contact">Request a quote</a> <a class="btn ghost" href="/projects">See our projects</a></div></section>
<section class="stats"><div class="wrap cols">${lines(s.stats).map(l=>{const[a,b]=l.split('|');return `<div><b>${e(a)}</b><span>${e(b)}</span></div>`}).join('')}</div></section>
<section class="wrap"><h2>What we do</h2><div class="grid">${d.services.map(v=>`<a class="card pad svc" href="/services/${e(v.slug)}"><small>${e(v.group)}</small><h3>${e(v.title)}</h3><p>${e(v.summary)}</p><span>Learn more →</span></a>`).join('')}</div></section>
<section class="band alt"><div class="wrap"><h2>Attention little leagues</h2><p>Full field construction, laser grading, irrigation, drainage, mounds, lip removal, clay and hydroseeding, built to fit league budgets.</p><a class="btn" href="/contact">Talk to us</a></div></section>
<section class="wrap"><h2>Recent projects</h2><div class="grid">${feat.map(projCard).join('')}</div><p><a href="/projects">View all projects →</a></p></section>
${d.testimonials.length?`<section class="wrap"><h2>What clients say</h2><div class="grid">${d.testimonials.map(t=>`<blockquote class="card pad">“${e(t.quote)}”<footer>${e(t.name)}${t.role?`, ${e(t.role)}`:''}</footer></blockquote>`).join('')}</div></section>`:''}${cta(d)}`}))});
app.get('/services',(q,r)=>{const d=load();r.send(layout(d,{title:`Athletic Field Services | ${d.site.name}`,desc:'Field construction, renovation, aeration, sod, irrigation, drainage and maintenance services.',p:'/services',body:`<section class="wrap"><h1>Our services</h1>${['Construction','Maintenance'].map(g=>`<h2>${g}</h2><div class="grid">${d.services.filter(v=>v.group===g).map(v=>`<a class="card pad svc" href="/services/${e(v.slug)}"><h3>${e(v.title)}</h3><p>${e(v.summary)}</p><span>Learn more →</span></a>`).join('')}</div>`).join('')}</section>${cta(d)}`}))});
app.get('/services/:slug',(q,r,n)=>{const d=load(),v=d.services.find(x=>x.slug===q.params.slug);if(!v)return n();const rel=d.projects.filter(p=>p.service===v.slug);
r.send(layout(d,{title:`${v.title} in CT & NY | ${d.site.name}`,desc:v.summary,p:'/services/'+v.slug,ld:{'@context':'https://schema.org','@type':'Service',name:v.title,description:v.summary,provider:{'@id':SITE+'/#org'},areaServed:d.site.areas},body:`<section class="wrap narrow"><p class="meta"><a href="/services">Services</a> / ${e(v.title)}</p><h1>${e(v.title)}</h1>${v.image?imgOr(v.image,v.title,'hero-img'):''}${paras(v.body)}<a class="btn" href="/contact?service=${e(v.slug)}">Request a quote</a></section>${rel.length?`<section class="wrap"><h2>Project examples</h2><div class="grid">${rel.map(projCard).join('')}</div></section>`:''}${cta(d)}`}))});
app.get('/projects',(q,r)=>{const d=load();r.send(layout(d,{title:`Completed Athletic Field Projects | ${d.site.name}`,desc:'Recent field construction and renovation projects for schools, parks and towns in Connecticut and New York.',p:'/projects',body:`<section class="wrap"><h1>Completed projects</h1><div class="grid">${d.projects.map(projCard).join('')}</div></section>${cta(d)}`}))});
app.get('/about',(q,r)=>{const d=load(),s=d.site;r.send(layout(d,{title:`About | ${s.name}`,desc:`${s.name} (formerly ${s.formerName}) brings 135+ years of combined experience to athletic field construction and maintenance.`,p:'/about',body:`<section class="wrap narrow"><h1>About ${e(s.name)}</h1><p>${e(s.name)}, formerly ${e(s.formerName)}, specializes in athletic field construction and maintenance for schools, municipalities and leagues in ${e(s.areas)}.</p><h2>Leadership</h2>${d.team.map(t=>`<div class="card pad"><h3>${e(t.name)}</h3><p class="meta">${e(t.title)}</p><p>${e(t.bio)}</p></div>`).join('')}</section>${cta(d)}`}))});
app.get('/contact',(q,r)=>{const d=load(),s=d.site;r.send(layout(d,{title:`Contact & Free Quote | ${s.name}`,desc:`Call ${s.phone} or request a quote for athletic field construction or maintenance.`,p:'/contact',body:`<section class="wrap narrow"><h1>Request a quote</h1>${q.query.sent?'<p class="ok">Thanks! We will be in touch shortly.</p>':''}<form method="post" action="/contact" class="form"><input name="website" class="hp" tabindex="-1" autocomplete="off"><label>Name<input name="name" required></label><label>Email<input name="email" type="email" required></label><label>Phone<input name="phone"></label><label>Organization<input name="org"></label><label>Service<select name="service"><option value="">Not sure yet</option>${d.services.map(v=>`<option value="${e(v.title)}"${q.query.service===v.slug?' selected':''}>${e(v.title)}</option>`).join('')}</select></label><label>Message<textarea name="message" rows="5"></textarea></label><button class="btn">Send request</button></form><p>Or call <a href="tel:${e(s.tel)}">${e(s.phone)}</a></p></section>`}))});
app.post('/contact',(q,r)=>{if(q.body.website)return r.redirect('/contact?sent=1');const d=load(),b=q.body;
d.inquiries.unshift({id:crypto.randomUUID(),date:new Date().toISOString(),...Object.fromEntries(['name','email','phone','org','service','message'].map(k=>[k,String(b[k]||'').slice(0,2000)]))});d.inquiries=d.inquiries.slice(0,300);save(d);r.redirect('/contact?sent=1')});
app.get('/robots.txt',(q,r)=>r.type('text').send(`User-agent: *\nAllow: /\nDisallow: /admin\nSitemap: ${SITE}/sitemap.xml\n`));
app.get('/sitemap.xml',(q,r)=>{const d=load(),u=['/','/services','/projects','/about','/contact',...d.services.map(v=>'/services/'+v.slug)];r.type('xml').send(`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${u.map(x=>`<url><loc>${SITE}${x}</loc></url>`).join('')}</urlset>`)});

/* ---------- admin ---------- */
const COLS={
projects:{label:'Projects',t:'title',f:[['title','Title'],['location','Location'],['year','Year'],['service','Service slug (links project to a service page)'],['featured','Show on home page? (yes/no)'],['image','Image URL or /img/file.jpg'],['scope','Scope (one item per line)','t']]},
testimonials:{label:'Testimonials',t:'name',f:[['name','Name'],['role','Role / organization'],['quote','Quote','t']]},
services:{label:'Services',t:'title',f:[['title','Title'],['slug','URL slug'],['group','Group (Construction or Maintenance)'],['summary','Short summary'],['image','Image URL'],['body','Page text (blank line between paragraphs)','t']]}};
const SET=[['heroTitle','Home headline'],['heroSub','Home sub-headline','t'],['phone','Phone (display)'],['tel','Phone (link, e.g. +12035692942)'],['email','Email'],['areas','Service areas (comma separated)'],['stats','Stats (one per line: 300+|Label)','t']];
const A=(b,t='Admin')=>`<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex"><title>${t}</title><link rel="stylesheet" href="/style.css"><body class="adm"><div class="wrap narrow">${b}</div>`;
const field=([k,l,t],v)=>`<label>${e(l)}${t?`<textarea name="${k}" rows="6">${e(v)}</textarea>`:`<input name="${k}" value="${e(v)}">`}</label>`;
const nav=`<p class="meta"><a href="/admin">Dashboard</a> · <a href="/" target="_blank">View site</a></p>`;
const tries={};
app.get('/admin',(q,r)=>{if(!PASS)return r.send(A('<h1>Admin disabled</h1><p>Set the ADMIN_PASSWORD environment variable.</p>'));
if(!authed(q))return r.send(A('<h1>Admin login</h1><form method="post" action="/admin/login" class="form"><label>Password<input type="password" name="password" autofocus></label><button class="btn">Log in</button></form>'+(q.query.err?'<p class="err">Wrong password.</p>':'')));
const d=load();r.send(A(`<h1>Dashboard</h1>${Object.entries(COLS).map(([k,c])=>`<p><a class="btn sm" href="/admin/${k}">${c.label} (${d[k].length})</a></p>`).join('')}<p><a class="btn sm" href="/admin/settings">Site settings</a></p><p><a class="btn sm" href="/admin/inquiries">Quote requests (${d.inquiries.length})</a></p><form method="post" action="/admin/logout"><button class="btn ghost sm">Log out</button></form>`))});
app.post('/admin/login',(q,r)=>{const ip=q.ip,t=tries[ip]=(tries[ip]||[]).filter(x=>x>Date.now()-9e5);
if(!PASS||t.length>=8||!eq(String(q.body.password||''),PASS)){t.push(Date.now());return r.redirect('/admin?err=1')}
const exp=Date.now()+7*864e5;r.setHeader('Set-Cookie',`s=${exp}.${sign(String(exp))}; HttpOnly; Secure; SameSite=Strict; Path=/admin; Max-Age=604800`);r.redirect('/admin')});
app.post('/admin/logout',(q,r)=>{r.setHeader('Set-Cookie','s=; Path=/admin; Max-Age=0');r.redirect('/admin')});
app.use('/admin',(q,r,n)=>authed(q)?n():r.redirect('/admin'));
app.get('/admin/settings',(q,r)=>{const s=load().site;r.send(A(`${nav}<h1>Site settings</h1><form method="post" class="form">${SET.map(f=>field(f,s[f[0]])).join('')}<button class="btn">Save</button></form>`))});
app.post('/admin/settings',(q,r)=>{const d=load();SET.forEach(([k])=>{if(q.body[k]!==undefined)d.site[k]=String(q.body[k]).trim()});save(d);r.redirect('/admin')});
app.get('/admin/inquiries',(q,r)=>{const d=load();r.send(A(`${nav}<h1>Quote requests</h1>${d.inquiries.map(i=>`<div class="card pad"><b>${e(i.name)}</b> · ${e(i.org)}<br><a href="mailto:${e(i.email)}">${e(i.email)}</a> ${e(i.phone)}<p class="meta">${e(i.date.slice(0,10))} · ${e(i.service)}</p><p>${e(i.message)}</p></div>`).join('')||'<p>None yet.</p>'}`))});
app.get('/admin/:col',(q,r,n)=>{const c=COLS[q.params.col];if(!c)return n();const d=load(),it=d[q.params.col].find(x=>x.id===q.query.edit)||{};
r.send(A(`${nav}<h1>${c.label}</h1><form method="post" action="/admin/${q.params.col}/save" class="form"><h2>${it.id?'Edit':'Add new'}</h2><input type="hidden" name="id" value="${e(it.id||'')}">${c.f.map(f=>field(f,it[f[0]])).join('')}<button class="btn">Save</button></form><h2>Existing</h2>${d[q.params.col].map(x=>`<div class="card pad row"><span>${e(x[c.t])}</span><span><a href="/admin/${q.params.col}?edit=${e(x.id)}">Edit</a> <form method="post" action="/admin/${q.params.col}/delete" style="display:inline" onsubmit="return confirm('Delete?')"><input type="hidden" name="id" value="${e(x.id)}"><button class="lnk">Delete</button></form></span></div>`).join('')}`))});
app.post('/admin/:col/save',(q,r,n)=>{const c=COLS[q.params.col];if(!c)return n();const d=load(),list=d[q.params.col],o={};
c.f.forEach(([k])=>o[k]=String(q.body[k]||'').trim().slice(0,10000));if(o.slug!==undefined)o.slug=slug(o.slug||o.title);
const i=list.findIndex(x=>x.id===q.body.id);if(i>=0)list[i]={...list[i],...o};else list.push({id:crypto.randomUUID(),...o});save(d);r.redirect('/admin/'+q.params.col)});
app.post('/admin/:col/delete',(q,r,n)=>{if(!COLS[q.params.col])return n();const d=load();d[q.params.col]=d[q.params.col].filter(x=>x.id!==q.body.id);save(d);r.redirect('/admin/'+q.params.col)});

app.use((q,r)=>r.status(404).send(layout(load(),{title:'Page not found',desc:'Page not found',body:'<section class="wrap"><h1>Page not found</h1><a href="/">Back home</a></section>'})));
app.listen(process.env.PORT||3000,()=>console.log('Greenway site running'));
