// Field definitions drive BOTH the admin forms and the data model.
// types: text | textarea | list (one per line) | select | multi | checkbox | number | image | images
const SPORTS = ['Baseball', 'Softball', 'Soccer', 'Football', 'Lacrosse', 'Multi-Sport'];
const CATS = ['build', 'renovate', 'fix', 'maintain', 'specialty'];
const seo = [
  { k: 'seoTitle', label: 'SEO title (≈60 chars)', type: 'text' },
  { k: 'seoDescription', label: 'SEO meta description (≈155 chars)', type: 'textarea' },
];
module.exports = {
  services: {
    label: 'Services', singular: 'Service', title: 'name', sort: 'order',
    fields: [
      { k: 'name', label: 'Service name', type: 'text', req: true },
      { k: 'slug', label: 'URL slug (auto if blank)', type: 'text' },
      { k: 'category', label: 'Category', type: 'select', options: CATS },
      { k: 'order', label: 'Sort order', type: 'number' },
      { k: 'icon', label: 'Icon key (drainage, irrigation, grading, sod, aeration, infield, lining, fertilization, weed, overseed, fence, mound, repair, construction, renovation, maintenance)', type: 'text' },
      { k: 'short', label: 'Short description (cards)', type: 'textarea' },
      { k: 'heroHeadline', label: 'Page headline', type: 'text' },
      { k: 'intro', label: 'Intro under headline', type: 'textarea' },
      { k: 'what', label: 'What is it? (paragraphs separated by blank line)', type: 'textarea' },
      { k: 'why', label: 'Why does a field need it? (one per line)', type: 'list' },
      { k: 'whatWeDo', label: 'What Greenway does (paragraphs)', type: 'textarea' },
      { k: 'signs', label: 'Signs your field may need this (one per line)', type: 'list' },
      { k: 'heroImage', label: 'Hero image', type: 'image' },
      { k: 'beforeImage', label: 'Before image', type: 'image' },
      { k: 'afterImage', label: 'After image', type: 'image' },
      { k: 'gallery', label: 'Gallery', type: 'images' },
      { k: 'videoUrl', label: 'Video (YouTube/Vimeo URL or MP4 path)', type: 'text' },
      { k: 'faqs', label: 'FAQs (one per line: Question :: Answer). Only add real ones.', type: 'textarea' },
      { k: 'relatedServices', label: 'Related services', type: 'multi', of: 'services' },
      { k: 'ctaLabel', label: 'Contextual CTA button (e.g. Request a Drainage Assessment)', type: 'text' },
      { k: 'ctaPrompt', label: 'Contextual CTA sentence', type: 'text' },
      ...seo,
      { k: 'published', label: 'Published', type: 'checkbox' },
    ],
  },
  projects: {
    label: 'Projects', singular: 'Project', title: 'name', sort: 'year',
    fields: [
      { k: 'name', label: 'Project name', type: 'text', req: true },
      { k: 'slug', label: 'URL slug (auto if blank)', type: 'text' },
      { k: 'city', label: 'City', type: 'text' },
      { k: 'state', label: 'State (e.g. CT)', type: 'text' },
      { k: 'year', label: 'Year completed', type: 'number' },
      { k: 'clientType', label: 'Client type', type: 'select', of: 'industries' },
      { k: 'sports', label: 'Sport / field type', type: 'select-multi', options: SPORTS },
      { k: 'projectType', label: 'Project type', type: 'select', options: ['New Construction', 'Renovation', 'Repair', 'Maintenance'] },
      { k: 'overview', label: 'Overview', type: 'textarea' },
      { k: 'challenge', label: 'The challenge', type: 'textarea' },
      { k: 'solution', label: 'The Greenway solution', type: 'textarea' },
      { k: 'scope', label: 'Scope of work (one per line)', type: 'list' },
      { k: 'result', label: 'The result', type: 'textarea' },
      { k: 'heroImage', label: 'Hero / cover photo', type: 'image' },
      { k: 'beforeImage', label: 'Before photo', type: 'image' },
      { k: 'afterImage', label: 'After photo', type: 'image' },
      { k: 'gallery', label: 'Project gallery', type: 'images' },
      { k: 'videoUrl', label: 'Video (YouTube/Vimeo URL or MP4 path)', type: 'text' },
      { k: 'services', label: 'Services used', type: 'multi', of: 'services' },
      { k: 'featured', label: 'Featured on homepage', type: 'checkbox' },
      ...seo,
      { k: 'published', label: 'Published', type: 'checkbox' },
    ],
  },
  testimonials: {
    label: 'Testimonials', singular: 'Testimonial', title: 'name',
    fields: [
      { k: 'quote', label: 'Quote (real quotes only)', type: 'textarea', req: true },
      { k: 'name', label: 'Name', type: 'text', req: true },
      { k: 'organization', label: 'Organization', type: 'text' },
      { k: 'role', label: 'Role', type: 'text' },
      { k: 'services', label: 'Related services', type: 'multi', of: 'services' },
      { k: 'project', label: 'Related project', type: 'select', of: 'projects' },
      { k: 'industries', label: 'Related industries', type: 'multi', of: 'industries' },
      { k: 'featured', label: 'Show on homepage', type: 'checkbox' },
      { k: 'published', label: 'Published', type: 'checkbox' },
    ],
  },
  industries: {
    label: 'Who We Serve', singular: 'Industry page', title: 'name', sort: 'order',
    fields: [
      { k: 'name', label: 'Name', type: 'text', req: true },
      { k: 'slug', label: 'URL slug (auto if blank)', type: 'text' },
      { k: 'order', label: 'Sort order', type: 'number' },
      { k: 'icon', label: 'Icon key (schools, municipalities, parks, colleges, sports, baseball, soccer)', type: 'text' },
      { k: 'short', label: 'Short description', type: 'textarea' },
      { k: 'intro', label: 'Page intro (paragraphs)', type: 'textarea' },
      { k: 'needs', label: 'What these organizations typically need (one per line)', type: 'list' },
      { k: 'heroImage', label: 'Hero image', type: 'image' },
      { k: 'services', label: 'Relevant services', type: 'multi', of: 'services' },
      ...seo,
      { k: 'published', label: 'Published', type: 'checkbox' },
    ],
  },
  team: {
    label: 'Team', singular: 'Team member', title: 'name', sort: 'order',
    fields: [
      { k: 'name', label: 'Name', type: 'text', req: true },
      { k: 'slug', label: 'Slug', type: 'text' },
      { k: 'title', label: 'Title', type: 'text' },
      { k: 'order', label: 'Sort order', type: 'number' },
      { k: 'bio', label: 'Bio (paragraphs)', type: 'textarea' },
      { k: 'photo', label: 'Photo', type: 'image' },
      { k: 'published', label: 'Published', type: 'checkbox' },
    ],
  },
  resources: {
    label: 'Resources', singular: 'Resource', title: 'title',
    fields: [
      { k: 'title', label: 'Title', type: 'text', req: true },
      { k: 'slug', label: 'URL slug (auto if blank)', type: 'text' },
      { k: 'type', label: 'Type', type: 'select', options: ['Guide', 'Article', 'Video', 'FAQ'] },
      { k: 'summary', label: 'Summary', type: 'textarea' },
      { k: 'body', label: 'Body (paragraphs; lines starting with "## " become headings)', type: 'textarea' },
      { k: 'image', label: 'Image', type: 'image' },
      { k: 'file', label: 'Downloadable file (PDF)', type: 'file' },
      { k: 'videoUrl', label: 'Video URL', type: 'text' },
      { k: 'featured', label: 'Feature as authority asset (homepage + resources)', type: 'checkbox' },
      ...seo,
      { k: 'published', label: 'Published', type: 'checkbox' },
    ],
  },
};
module.exports.SPORTS = SPORTS;
module.exports.CATS = CATS;
